ErpProject/Models/AttendanceAndDeparture.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ErpProject.Models
{
    public class AttendanceAndDeparture
    {
        public int Id { get; set; }
        public DateOnly Date { get; set; }
        public TimeOnly TimeIn { get; set; }
        public TimeOnly TimeOut {  get; set; }
        public decimal? HourLate { get; set; }
        public decimal? DiscountValue { get; set; }
        [ForeignKey(nameof(Employee))]
        public int? EmployeeId { get; set; }
        public Employee? Employee { get; set; }

    }
}

ErpProject/Controllers/AttendanceAndDepartureController.cs
using Microsoft.AspNetCore.Mvc;
using ErpProject.Models;
using ErpProject.Data;
using ErpProject.Repository.Basic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using ErpProject.Service;
using Microsoft.AspNetCore.Authorization;
using ErpProject.Constant;

namespace ErpProject.Controllers
{
    [Authorize(Policy = Permissions.AttendanceAndDeparture.View)]
    public class AttendanceAndDepartureController : Controller
    {
        private readonly ErpDbContext _context;
        private readonly IRepository<AttendanceAndDeparture> _repository;
        private readonly DiscountOperations _discountOperations;
        public AttendanceAndDepartureController(ErpDbContext context, IRepository<AttendanceAndDeparture> repository)
        {
            _context = context;
            _repository = repository;
            _discountOperations=new DiscountOperations(context);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var entites = await _context.Set<AttendanceAndDeparture>().Include(e=>e.Employee).ToListAsync();
            return View(entites);
        }

        [Authorize(Policy = Permissions.Catigory.Creat)]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await ViewBages();
            return View();
        }
        [Authorize(Policy = Permissions.Catigory.Creat)]
        [HttpPost]
        public async Task<IActionResult> Create(AttendanceAndDeparture entity)
        {
            await ViewBages();
            _discountOperations.Opearation(entity);
            if (ModelState.IsValid)
            {
                await _repository.AddAsync(entity);
                return RedirectToAction(nameof(Index));
            }
            return View(entity);
        }

        [Authorize(Policy = Permissions.Catigory.Edit)]
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            await ViewBages();
            var entity = await _repository.GetByIdAsync(id);
            return View(entity);
        }
        [Authorize(Policy = Permissions.Catigory.Edit)]
        [HttpPost]
        public async Task<IActionResult> Update(AttendanceAndDeparture entity)
        {
            await ViewBages();
            _discountOperations.Opearation(entity);
            if (ModelState.IsValid)
            {
                _repository.Update(entity);
                return RedirectToAction(nameof(Index));
            }
            return View(entity);
        }

        [Authorize(Policy = Permissions.Catigory.Delet)]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var entity = await _repository.GetByIdAsync(id);
            if (entity != null)
            {
                _repository.Delete(entity);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }


        public async Task ViewBages()
        {
            var employes = await _context.employees.ToListAsync();
            SelectList selectEmployees = new SelectList(employes, "Id", "Name");
            ViewBag.Employes = selectEmployees;
            
        }
    }
}

ErpProject/Views/AttendanceAndDeparture/Create.cshtml
@model AttendanceAndDeparture

@{
    ViewData["Title"] = "Creat Att,Dep";
}
<link href="~/css/form.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<style>
    .validatin-dngare{
        color:red;
    }
</style>
<div class="form-flex">
    <div class="headtitle">
        <h3>Creat AttendanceAndDeparture</h3>
    </div>
    <div class="form-content">
        <div class="hiderrcont" style="display: flex;">
            <h4 style="color: #177ae0 !important;border-bottom:solid #177ae0 1px  ;"><i class="fas fa-cogs"></i> Genral detailes</h4>
        </div>
        <form asp-action="Create" asp-controller="AttendanceAndDeparture">
            <div style="width: 100%; display:flex; justify-content:space-between">
                <div class="custom-picker" style="width:48%;">
                    <label> Attendance Time </label>
                    <input type="time" asp-for="TimeIn" id="styledTime" placeholder="Select Date From" style="color: white;">
                    <span class="validatin-dngare" asp-validation-for="TimeIn"></span>
                </div>
                <div class="custom-picker" style="width:48%;">
                    <label> Departure Time Out</label>
                    <input type="time" asp-for="TimeOut" id="styledTime" placeholder="Select Date To" style="color: white;">
                    <span class="validatin-dngare" asp-validation-for="TimeOut"></span>
                </div>
            </div>
            <div class="custom-picker" style="width: 100%;">
                <label> Attendance And Departure Date</label>
                <input type="date" asp-for="Date" id="styledDate" placeholder="Select Date" style="color: white;">
                <span class="validatin-dngare" asp-validation-for="Date"></span>
            </div>
            <div class="form-input" style="width:100%">
                <label asp-for="EmployeeId">Employee</label>
                <select style="margin-top:5px" class="catigory" asp-for="EmployeeId" asp-items="@ViewBag.Employes">
                </select>
            </div>
            <div class="form-groupflex" style="width:100%;">
                <div class="form-label">
                    <label asp-for="HourLate">Hourse Late Price</label>
                </div>
                <div class="form-input">
                    <input type="text" asp-for="HourLate" placeholder=" Hourse Lat ..." />
                </div>
                <span class="validatin-dngare" asp-validation-for="HourLate"></span>
            </div>


            <div class="submit-buuton">
                <button type="submit" class="submit1" >
                    Next step<i class="fas fa-arrow-right" style="padding-left:8px; "></i>
                </button>
            </div>
                
    </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr("#styledDate", {
            altInput: true,
            altFormat: "F j, Y",
            dateFormat: "Y-m-d",
        });
        flatpickr("#styledTime", {

            enableTime: true,
            noCalendar: true,
            dateFormat: "H:i",
        });
    </script>
}

ErpProject/Views/AttendanceAndDeparture/Index.cshtml
@model IEnumerable<AttendanceAndDeparture>

@{
    ViewData["Title"] = "Att,Deps ";
}
<link href="~/css/table.css" rel="stylesheet"/>
<div class="rightside-flex">
    <div class="table-content">
        <h4 class="table-name">AttendanceAndDepartures</h4>
        <table class="table">
            <thead> 
                <div class="flexitem" >
                    <div class="searchadd">
                       
                        <a class="addbutton" asp-action="Create" ><i class="fas fa-plus" style="color: white; padding-right:5px ;"></i> Add AttendanceAndDeparture</a>
                    </div>
                </div>
                <th>ID</th>
                <th>Employee Name</th>
                <th>Att , Dep Date</th>
                <th>Attendance Time</th>
                <th>Departure Time</th>
                <th> Att , Dep HourLate</th>
                <th> Total Discount</th>
                <th style="width: 150px;">Action</th>
            </thead>
            <tbody>
                @foreach(var attendanceanddeparture in Model){
                    <tr>
                        <td>@attendanceanddeparture.Id</td>
                        <td>@attendanceanddeparture.Employee.Name</td>
                        <td>@attendanceanddeparture.Date</td>
                        <td>@attendanceanddeparture.TimeIn</td>
                        <td>@attendanceanddeparture.TimeOut</td>
                        <td>@attendanceanddeparture.HourLate</td>
                        <td>@attendanceanddeparture.DiscountValue</td>
                        <td class="action">
                            <div class="action-edit">
                                <a class="edit" asp-action="Detailes" asp-route-Id="@attendanceanddeparture.Id"><i class="fas fa-portrait"></i></a>
                            </div>
                            <div class="action-edit">
                                <a class="edit" asp-action="Update" asp-route-Id="@attendanceanddeparture.Id"><i class="fas fa-edit"></i></a>
                            </div>
                            <div class="action-delet">
                                <a class="delet" data-id="@attendanceanddeparture.Id"><i class="fas fa-trash"></i></a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="previousbt" >
         </div>
    </div>
</div>
<div class="card-confierm" style="position: absolute; top: 10px; left: 50%; width: 300px; height: 165px;">
    <div style="position: relative;top: 35%;"><h4 style="color: white;text-align: center;">Are you sure Delet Item</h4></div>
    <div class="card-content">
        <div class="yes"><a href="" class="yeslink" style="color: white;" >Yes</a></div>
        <div class="no"><a asp-action="Index" style="color: white;">No</a></div>
    </div>
</div>

@section Scripts {
    <script>
        let delet = document.querySelectorAll(".delet");
        let yes = document.getElementsByClassName("yeslink")[0];
        let cardconfierm = document.getElementsByClassName("card-confierm")[0];
        for (let i = 0; i < delet.length; i++) {
            delet[i].onclick = function () {
                if (cardconfierm.className == 'card-confierm') {
                    cardconfierm.className = 'card-confiermshow';
                }
                else {
                    cardconfierm.className = 'card-confierm';
                }
                let attendanceanddepartureId = this.getAttribute('data-id');
                yes.href = `/AttendanceAndDeparture/Delete/${attendanceanddepartureId}`;

            }
        }
    </script>
}

ErpProject/Views/AttendanceAndDeparture/Update.cshtml
@model AttendanceAndDeparture

@{
    ViewData["Title"] = "Update Att,Dep ";
}
<link href="~/css/form.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<style>
    .validatin-dngare {
        color: red;
    }
</style>
<div class="form-flex">
    <div class="headtitle">
        <h3>Update Attendance And Departure</h3>
    </div>
    <div class="form-content">
        <div class="hiderrcont" style="display: flex;">
            <h4 style="color: #177ae0 !important;border-bottom:solid #177ae0 1px  ;"><i class="fas fa-cogs"></i> Genral detailes</h4>
        </div>
        <form asp-action="Update" asp-controller="AttendanceAndDeparture">
            <div style="width: 100%; display:flex; justify-content:space-between">
                <div class="custom-picker" style="width:48%;">
                    <label> Attendance Time </label>
                    <input type="time" asp-for="TimeIn" id="styledTime" placeholder="Select Date From" style="color: white;">
                    <span class="validatin-dngare" asp-validation-for="TimeIn"></span>
                </div>
                <div class="custom-picker" style="width:48%;">
                    <label> Departure Time Out</label>
                    <input type="time" asp-for="TimeOut" id="styledTime" placeholder="Select Date To" style="color: white;">
                    <span class="validatin-dngare" asp-validation-for="TimeOut"></span>
                </div>
            </div>
            <div class="custom-picker" style="width: 100%;">
                <label> Attendance And Departure Date</label>
                <input type="date" asp-for="Date" id="styledDate" placeholder="Select Date" style="color: white;">
                <span class="validatin-dngare" asp-validation-for="Date"></span>
            </div>
            <div class="form-input" style="width:100%">
                <label asp-for="EmployeeId">Employee</label>
                <select style="margin-top:5px" class="catigory" asp-for="EmployeeId" asp-items="@ViewBag.Employes">
                </select>
            </div>
            <div class="form-groupflex" style="width:100%;">
                <div class="form-label">
                    <label asp-for="HourLate">Hourse Late Price</label>
                </div>
                <div class="form-input">
                    <input type="text" asp-for="HourLate" placeholder=" Hourse Lat ..." />
                </div>
                <span class="validatin-dngare" asp-validation-for="HourLate"></span>
            </div>


            <div class="submit-buuton">
                <button type="submit" class="submit1">
                    Next step<i class="fas fa-arrow-right" style="padding-left:8px; "></i>
                </button>
            </div>

        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr("#styledDate", {
            altInput: true,
            altFormat: "F j, Y",
            dateFormat: "Y-m-d",
        });
        flatpickr("#styledTime", {

            enableTime: true,
            noCalendar: true,
            dateFormat: "H:i",
        });
    </script>
}